---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: streama
  name: streama
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: streama
  type: ClusterIP
